spring:
  application:
    name: gateway-client
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      server:
        webflux:
          routes:
            - id: order-client
              uri : lb://order-client
              predicates:
                - Path=/order/**

            - id: product-client
              uri: lb://product-client
              predicates:
                - Path=/product/**

            - id: auth-client
              uri: lb://auth-client
              predicates:
                - Path=/auth/**

server:
  port: 19091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

