spring:
  application:
    name: gateway-client
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: order-client
              uri: http://localhost:19092
              predicates:
                  - Path=/orders/**

            - id: product-client-1
              uri: http://localhost:19093
              predicates:
                  - Path=/products/**
                  - Weight=group-product-api, 7

            - id: product-client-2
              uri: http://localhost:19094
              predicates:
                - Path=/products/**
                - Weight=group-product-api, 3

            - id: auth-client
              uri: lb://auth-client
              predicates:
                  - Path=/auth/**

server:
  port: 19091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

