spring:
  application:
    name: order-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nbcamp
    username: root
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  data:
    redis:
      host: default
      port: 6379
      ssl:
        enabled: true



server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

resilience4j:
  circuit breaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 60000
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state:
          seconds: 20
management:
  endpoint:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0